apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  imagePullSecrets:
  - name: aliyun-cr
  containers:
  - name: liveness
    image: registry-vpc.cn-hangzhou.aliyuncs.com/k8s-expe/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
