apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: influxdb
    image: influxdb
  dnsPolicy: ClusterFirstWithHostNet
# apiVersion: v1
# kind: Pod
# metadata:
#   name: influxdb
#   namespace: default
# spec:
#   containers:
#   - name: influxdb
#     image: influxdb
#     ports:
#     - name: http
#       containerPort: 8086
#       hostPort: 8086