apiVersion: v1
kind: Pod
metadata:
  name: pod-using-hostport
  labels:
    name: pod-using-hostport
spec:
  containers:
  - name: demo
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
      hostPort: 10080