apiVersion: v1
kind: Pod
metadata:
  name: pod-demo-with-cmd-and-args
spec:
  containers:
  - name: demo
    image: ikubernetes/demoapp:v1.0
    command:
    - /bin/sh
    - -c
    args:
    - python3 /usr/local/bin/demo.py -p 8080
    ports:
    - containerPort: 8080
