apiVersion: v1
kind: Pod
metadata:
  name: pod-using-env
spec:
  containers:
  - name: demo
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    env:
    - name: HOST
      value: "127.0.0.1"
    - name: PORT
      value: "8080"
    ports:
    - containerPort: 8080
