apiVersion: v1
kind: Pod
metadata:
  name: pod-using-hostnetwork
  labels:
    name: pod-using-hostnetwork
spec:
  containers:
  - name: demo
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
  hostNetwork: true