apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
  labels:
    lableA: labelA
    labelB: labelB
    labelC: labelC
  annotations:
    annotation1: annotation1
    annotation2: annotation2
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "sleep 3600"]
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: MY_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: MY_LABEL_B
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['labelB']
    - name: MY_ANNOTATION_2
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['annotation2']
    - name: GREETING
      value: "Hello World"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  restartPolicy: Never
