apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
    - key: env
      operator: In 
      values:
      - prod
  template:
    metadata:
      labels:
        app: tomcat
        tier: frontend
        env: prod
    spec:
      containers:
      - name: tomcat-demo
        image: tomcat:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - port: 8080
    targetPort: 8080
    name: service-port
  - name: shutdown-port
    port: 8005
    targetPort: 8005
