apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2020-07-13T07:50:55Z
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: jst-nas-code
  name: jst-nas-code
  resourceVersion: "2647261492"
  selfLink: /api/v1/persistentvolumes/jst-nas-code
  uid: 95256f96-c4dd-11ea-af1c-f21e0927934a
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jst-nas-code
    namespace: jst-default
    resourceVersion: "2647261489"
    uid: 9ba438c7-c4dd-11ea-af1c-f21e0927934a
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /data/project
      server: 9dc334bbec-hva23.cn-zhangjiakou.nas.aliyuncs.com
      vers: "3"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
status:
  phase: Bound