apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul
    chart: consul-helm
    component: server
    hasDNS: "true"
    release: consul
  name: data-consul-consul-server-0
  namespace: consul
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
status:
  phase: Pending
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul
    chart: consul-helm
    component: server
    hasDNS: "true"
    release: consul
  name: data-consul-consul-server-1
  namespace: consul
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
status:
  phase: Pending
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul
    chart: consul-helm
    component: server
    hasDNS: "true"
    release: consul
  name: data-consul-consul-server-2
  namespace: consul
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
status:
  phase: Pending

